# action.yml
name: 'Build pla artefacts'
description: 'Generate some installable packeges for your code'
inputs:
  keystore-base64:  
    description: 'base64 serilized keystore'
    required: true
  keystore-pass:
    description: 'password required to open keystore'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: "composite"
  steps:
    - run: pwd
      shell: bash
      
    - run: |
        wget -O pla-sdk.zip https://github.com/Lopla/Pla/archive/refs/heads/master_2021-01-04-02-44-07.zip
        unzip pla-sdk.zip
        mv  Pla-refs-heads-master_2021-01-04-02-44-07/Pla.Mobile/ ./Pla.Mobile
      shell: bash
      name: Downloading pla platform sdk
      
    - run: ls
      shell: bash

    - run: |
        cd Pla.Mobile
        nuget restore Pla.Mobile.sln
        cd Pla.Mobile.Android
        msbuild /p:Configuration=Release /t:PackageForAndroid  Pla.Mobile.Android.csproj
        echo ${{ inputs.keystore-base64 }} | base64 --decode > keystore
        jarsigner -verbose -sigalg MD5withRSA -digestalg SHA1 -keystore keystore -storepass ${{ inputs.keystore-pass }} -signedjar ~/pla_signed.apk bin/Release/com.companyname.pla.mobile.apk Pla
        ~/Library/Android/sdk/build-tools/30.0.1/zipalign -f -v 4 ~/pla_signed.apk ~/pla.apk
      shell: bash
  
