# action.yml
name: 'Build pla artefacts'
description: 'Generate some installable packeges for your code'
inputs:
  keystore-base64:  
    description: 'base64 serilized keystore'
    required: true
  keystore-pass:
    description: 'password required to open keystore'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.keystore-base64 }}
    - ${{ inputs.keystore-pass }}
